utils::globalVariables(c(
":=","AEACNOT1","AEACNOT2","AEDECOD","AEDTHDTC","AEDTIMP","AEENDTC","AELAT","AEMODIFY",
"AEOUT","AESDTH","AESEV","AESOC","AESTDTC","AETERM","AETOXGR","BCVATOT_CRF",
"BCVATOT_DERIVED","BCVA_1M_TOTAL","BCVA_4M_TOTAL",
"CEDTC","CESTDTC","CEENDTC","CMCAT","CMDECOD","CMENDTC",
"CMINDC","CMLAT","CMPROPH","CMROUTE","CMSTDTC","DATE","DIABP","DISCFL","DSCAT","DSDECOD",
"DSSCAT","DSSPID","DSSTDTC","DSSTDTC_imp","DSSTDTIMP","DSTERM","DS_RANDDT","DT1","DT2",
"DTHDTC","DVEPRELI","DVREAS","EARLIEST_DTHDT","EARLIEST_DTHDTC","ECCAT","ECLAT",
"ECLOC","ECMOOD","ECOCCUR","ECROUTE","EXDOSE","EXDOSU","EXENDTC","EXENDTC_imp",
"EXOCCUR","EXSTDTC","EXSTDTC_imp","EXTRT","FLAG","Freq","LAG_OESTRESN","LBDTC",
"LBMETHOD","LBORRES","LBSTNRHI","LBSTNRLO","LBSTRESN","LBTEST","LBTESTCD",
"LEAD_OESTRESN","MAX_ROW","MHENDTC","MHSTDTC","MISFLAG","MISPEC","nickname","OECAT","OEDTC","OEDY",
"OELAT","OELOC","OERESCAT","OESCAT","OESPID","OESTAT","OESTRESN","OESTRESN.x",
"OESTRESN.y","OETESTCD","OETSTDTL","PARTB_CONST","PRCAT","PRENDTC","PRLAT","PROCCUR",
"PRPRESP","PRSTDTC","QSCAT","QSDTC","QSDTC1","QSORRES","QSREASND","QSSTAT","QSSTRESC",
"QSTESTCD","RAVE","REFTERM","ROW","ROWNUM","RSDTC","RSEVAL","RSORRES","RSSTAT","SCCAT","SCDTC",
"SCORRES","SCTEST","SCTESTCD","SC_STUDYEYE","SITEID","SSDTC","SSORRES","SSSTAT","SYSBP",
"TOTAL","TOT_1M","TOT_4M","TRDTC","TREVAL","TRTESTCD","TSPARMCD","TSVAL","TUDTC","TUEVAL",
"TULOC","TUORRES","USUBJID","VISIT","VISITNUM","VSDTC","VSDTC.SYSBP","VSORRES","VSSPID",
"VSSTRESN","VSTEST","VSTESTCD","Var1","Var2","check_stat","icdate","issue",
"lowvision_ind","max_STDEND","num_of_dates","sdtmchecksmeta", "subj_discont_fl","subject_id",
"check","fxn_in","LBSTAT","LBSTRESU",
"category","priority","pdf_title","xls_title","domains","pdf_subtitle", "ui", "server", "runGadget", "viewer", "req",
"x","Status"



))